import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react"
import {
  Home01Icon,
  CompassIcon,
  PieChartIcon,
  UserGroupIcon,
  AiSparklesIcon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  Add01Icon,
  Search01Icon,
  Notification02Icon,
  Wallet02Icon,
  BankIcon,
  CheckmarkCircle01Icon,
  Tick02Icon,
  AlertCircleIcon,
  Alert02Icon,
  Cancel01Icon,
  ViewIcon,
  SecurityCheckIcon,
  ReceiptIcon,
  Time01Icon,
  TrendingUpIcon,
  TrendingDownIcon,
  Briefcase01Icon,
  GraduationCapIcon,
  Airplane02Icon,
  LaptopIcon,
  PiggyBankIcon,
  MoneySend01Icon,
  CalculatorIcon,
  Calendar01Icon,
  InformationCircleIcon,
  Share01Icon,
  Bookmark02Icon,
  StarIcon,
  Settings02Icon,
  Call02Icon,
  SentIcon,
  PauseIcon,
  PlayIcon,
  FlashIcon,
  Target02Icon,
  GiftIcon,
  PercentIcon,
  Invoice01Icon,
  Copy01Icon,
  RefreshIcon,
  MoreHorizontalIcon,
  FilterIcon,
  GlobeIcon,
  LockIcon,
  Camera01Icon,
  Attachment02Icon,
  FireIcon,
  IdeaIcon,
  MinusSignIcon,
  Edit02Icon,
  CheckmarkBadge01Icon,
  Money03Icon,
  Analytics01Icon,
  NewsIcon,
  BookOpen01Icon,
  BanknoteIcon,
  CreditCardIcon,
  Exchange01Icon,
  HandCoinsIcon,
  RocketIcon,
  Navigation01Icon,
  Award01Icon,
  CrownIcon,
  Medal01Icon,
  Comment01Icon,
  Mic01Icon,
  MicOff01Icon,
  VolumeHighIcon,
  SmartPhone01Icon,
  SignalFull01Icon,
  Wifi01Icon,
  BatteryFullIcon,
  CircleIcon,
  RupeeCircleIcon,
  Coins01Icon,
  IndianRupeeIcon,
  AiBrain01Icon,
  ChartLineData01Icon,
  ShieldIcon,
  Delete02Icon,
  UserCircleIcon,
  StoreLocation01Icon,
  Time02Icon,
  PackageIcon,
  DeliveryBox01Icon,
  ChartHistogramIcon,
  CircleArrowUpRight02Icon,
  CircleArrowDownRightIcon,
  UserIcon,
  EnergyIcon,
  NotebookIcon,
  AiMicIcon,
  BubbleChatIcon,
  FileVerifiedIcon,
  HelpCircleIcon,
  SquareLock01Icon,
} from "@hugeicons/core-free-icons"
import { cn } from "@/lib/utils"

export const icons = {
  home: Home01Icon,
  compass: CompassIcon,
  pie: PieChartIcon,
  users: UserGroupIcon,
  sparkles: AiSparklesIcon,
  back: ArrowLeft01Icon,
  next: ArrowRight01Icon,
  down: ArrowDown01Icon,
  up: ArrowUp01Icon,
  plus: Add01Icon,
  search: Search01Icon,
  bell: Notification02Icon,
  wallet: Wallet02Icon,
  bank: BankIcon,
  check: CheckmarkCircle01Icon,
  tick: Tick02Icon,
  alert: AlertCircleIcon,
  warn: Alert02Icon,
  close: Cancel01Icon,
  eye: ViewIcon,
  shield: SecurityCheckIcon,
  shieldPlain: ShieldIcon,
  receipt: ReceiptIcon,
  time: Time01Icon,
  clock: Time02Icon,
  up2: TrendingUpIcon,
  down2: TrendingDownIcon,
  briefcase: Briefcase01Icon,
  grad: GraduationCapIcon,
  plane: Airplane02Icon,
  laptop: LaptopIcon,
  piggy: PiggyBankIcon,
  send: MoneySend01Icon,
  calc: CalculatorIcon,
  calendar: Calendar01Icon,
  info: InformationCircleIcon,
  share: Share01Icon,
  bookmark: Bookmark02Icon,
  star: StarIcon,
  settings: Settings02Icon,
  call: Call02Icon,
  sent: SentIcon,
  pause: PauseIcon,
  play: PlayIcon,
  flash: FlashIcon,
  target: Target02Icon,
  gift: GiftIcon,
  percent: PercentIcon,
  invoice: Invoice01Icon,
  copy: Copy01Icon,
  refresh: RefreshIcon,
  more: MoreHorizontalIcon,
  filter: FilterIcon,
  globe: GlobeIcon,
  lock: LockIcon,
  camera: Camera01Icon,
  attach: Attachment02Icon,
  fire: FireIcon,
  idea: IdeaIcon,
  minus: MinusSignIcon,
  edit: Edit02Icon,
  badgeCheck: CheckmarkBadge01Icon,
  money: Money03Icon,
  analytics: Analytics01Icon,
  news: NewsIcon,
  book: BookOpen01Icon,
  banknote: BanknoteIcon,
  card: CreditCardIcon,
  exchange: Exchange01Icon,
  handCoins: HandCoinsIcon,
  rocket: RocketIcon,
  nav: Navigation01Icon,
  award: Award01Icon,
  crown: CrownIcon,
  medal: Medal01Icon,
  comment: Comment01Icon,
  mic: Mic01Icon,
  micOff: MicOff01Icon,
  volume: VolumeHighIcon,
  phone: SmartPhone01Icon,
  signal: SignalFull01Icon,
  wifi: Wifi01Icon,
  battery: BatteryFullIcon,
  circle: CircleIcon,
  rupee: RupeeCircleIcon,
  rupeePlain: IndianRupeeIcon,
  coins: Coins01Icon,
  brain: AiBrain01Icon,
  chart: ChartLineData01Icon,
  chartHist: ChartHistogramIcon,
  trash: Delete02Icon,
  userCircle: UserCircleIcon,
  user: UserIcon,
  store: StoreLocation01Icon,
  package: PackageIcon,
  box: DeliveryBox01Icon,
  upRight: CircleArrowUpRight02Icon,
  downRight: CircleArrowDownRightIcon,
  energy: EnergyIcon,
  notebook: NotebookIcon,
  aiMic: AiMicIcon,
  chat: BubbleChatIcon,
  fileVerified: FileVerifiedIcon,
  help: HelpCircleIcon,
  lockSquare: SquareLock01Icon,
} satisfies Record<string, IconSvgElement>

export type IconName = keyof typeof icons

export function Icon({
  name,
  className,
  size = 20,
  strokeWidth = 1.8,
}: {
  name: IconName
  className?: string
  size?: number
  strokeWidth?: number
}) {
  return (
    <HugeiconsIcon
      icon={icons[name]}
      size={size}
      strokeWidth={strokeWidth}
      className={cn("shrink-0", className)}
    />
  )
}
